version: '4.30'

services:
  db:
    image: mongo:7
    restart: always
    ports: 
      - 27017:27017
    environment:
      MONGODB_DATABASE: ${MONGO_DB_NAME}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
    volumes:
      - ./mongo:/data/db